### ISSUE TITLE
我直接复制的整段cook为啥报错了

### ISSUE THREAD

**Issue by ewfubwefwe** [Wyatt1026/BilibiliDailyUp#1]
![image](https://user-images.githubusercontent.com/91933542/185556073-74e79d03-3e5f-41e9-8c78-353bd54690c5.png)
![image](https://user-images.githubusercontent.com/91933542/185556123-e50eb251-f95e-4034-bbc0-54a4b2edf6b0.png)
我用的这段cook，加下面会报错

**Comment by Wyatt1026** [comment]
可能是cookie抓错了。可以重新抓取试一试

**Comment by 76249** [comment]
方括号里可以改成双引号，cookie中会含有单引号所以会报错
