### ISSUE TITLE
请问多账号cookie的怎么填

### ISSUE THREAD

**Issue by magiccode1412** [Wyatt1026/BilibiliDailyUp#10]
单账号可行，但是想填写两个账号时遇到了困难，所以特来请教多账号cookie的填写示范，谢谢

**Comment by qilishidai** [comment]
后面加逗号，继续写
```python
COOKIE_LIST = [
    # 示例，以分号+空格分割，否则会出错。或者直接用原来方法获取后粘贴
    r"DedeUserID=xxxx; SESSDATA=xxxx; bili_jct=xxxx",
    r"DedeUserID=xxxx; SESSDATA=xxxx; bili_jct=xxxx",
               ]
```

多账号用原来方法的获取Cookie方法会有问题，因为退出登录后cookie会失效，解决办法是换多几个浏览器，或者无痕模式获取。具体如下
1. 浏览器无痕模式打开并登录 [bilibili 网站](https://www.bilibili.com/)。
2. 按 F12 打开 「开发者工具」 找到 应用程序/Application -\> 存储 -\> Cookies
3. 找到 `bili_jct` `SESSDATA` `DEDEUSERID` 三项，并复制值，
4.将上面复制值填入r"DedeUserID=xxxx; SESSDATA=xxxx; bili_jct=xxxx"，并填入配置文件`config/config.py`的`COOKIE_LIST `中。多个账号用，分割。形成一个列表

**Comment by Wyatt1026** [comment]
hey,感谢你发现问题并提供代码，已合并分支，最近在期末周比较忙才看见消息，感谢反馈，cookie的问题我一般浏览器是不退出登陆的,所以之前并没有发现你说的问题，多账号你可以打开另一个浏览器来实现多账号，因为我本身只有一个账号所以并未测试多账号

**Comment by magiccode1412** [comment]
非常感谢，已解决
