### ISSUE TITLE
青龙面板：建议增加从青龙面板的环境变量中读取cookie

### ISSUE THREAD

**Issue by magiccode1412** [Wyatt1026/BilibiliDailyUp#12]
从面板环境变量读取cookie可以更方便更改cookie，不用打开config文件修改，拉库和安装依赖也可以直接使用青龙面板的订阅功能，不需要用命令行

**Comment by Wyatt1026** [comment]
很久没有维护这个项目了。已经添加了。在青龙面板设置BILIBILI这个环境变量即可

**Comment by magiccode1412** [comment]
> 很久没有维护这个项目了。已经添加了。在青龙面板设置BILIBILI这个环境变量即可

谢谢，不过项目依然坚挺，现在还是有效的
