### ISSUE TITLE
python3.10下报错AttributeError: module 'collections' has no attribute 'MutableMapping'  

### ISSUE THREAD

**Issue by gitzhul** [Wyatt1026/BilibiliDailyUp#13]
使用青龙面板v2.16.2，内置的python版本是3.10，已安装requests，报错信息如下：
Traceback (most recent call last):
  File "/ql/data/scripts/BilibiliDailyUp-g/main.py", line 7, in <module>
    from core.bilibili import Bilibili
  File "/ql/data/scripts/BilibiliDailyUp-g/core/bilibili.py", line 5, in <module>
    import requests
  File "/usr/local/lib/python3.10/site-packages/requests/__init__.py", line 60, in <module>
    from . import utils
  File "/usr/local/lib/python3.10/site-packages/requests/utils.py", line 32, in <module>
    from .cookies import cookiejar_from_dict
  File "/usr/local/lib/python3.10/site-packages/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
查询原因是不兼容  大佬能否适配下

**Comment by Wyatt1026** [comment]
Hey. 能否提供复现的cookie格式。 看样子好像是cookie的格式造成的。但是我测试是没有问题的。无法复现这个报错。我在青龙面板再次测试了一遍也没有问题

**Comment by gitzhul** [comment]
你好 抱歉回复的比较晚  cookie是这样的
COOKIE_LIST = [r"PVID=1; buvid_fp_plain=undefined; sid=oxcd7spq; buvid_fp=39fc9ec34941cb57c13963a49069cad0; b_ut=5; i-wanna-go-back=-1; buvid4=FFF0C75B-E09F-494F-E80F-2B546D2EBAC412454-022060405-%2B%2BMbHGigSXFu7zU7mXhkBw%3D%3D; b_nut=1654202112; buvid3=CC474E28-BF8E-9069-CB6B-2A9B83ACBADA12454infoc; fingerprint=20fc9ec34941cb57c13963a49069cad0; _uuid=7BC28B109-4262-2552-19B3-810E5A7C10101D410602infoc; ogv_channel_version=v1; b_lsid=E511D2A92_18829126C85; innersign=0; deviceFingerprint=0a3c4f5f63bfc8c469fe8c751324faed; SESSDATA=4d4c4836%2C2699869714%2Cb89e8%2A51; bili_jct=51adc5c1f69073a12c532965cdf0e984; DedeUserID=XXXXXXXX; DedeUserID__ckMd5=XXXXXXXXXXXXX"]

**Comment by zhemed** [comment]
没有交流群吗，青龙拉完库怎么用啊，没看到有脚本啊

**Comment by gitzhul** [comment]
我回退版本了 不追新了 就这样吧 感谢大佬的贡献
