### ISSUE TITLE
提示错误，大佬

### ISSUE THREAD

**Issue by zxccxz-web** [Wyatt1026/BilibiliDailyUp#15]
![image](https://github.com/Wyatt1026/BilibiliDailyUp/assets/110436707/7704d28e-92ed-45ad-922e-a19eb041a561)

**Comment by Wyatt1026** [comment]
我刚测试了没问题。看样子是cookie的问题。 建议在F12 ![](https://img.itsopenai.com/i/2023/10/13/ytk3ub-2.webp) 过滤抓info这个包的cookie

**Comment by nizhenyu2022** [comment]
ck没抓全，少了bili_jct

**Comment by zxccxz-web** [comment]
![image](https://github.com/Wyatt1026/BilibiliDailyUp/assets/110436707/3267227b-c4d3-4ba4-80eb-3d340b56ea67)
还是一样，而且没有找到info这个包

**Comment by zxccxz-web** [comment]
![image](https://github.com/Wyatt1026/BilibiliDailyUp/assets/110436707/e0e6ae86-0ac3-4a09-adc6-87fb03f876e3)
