### ISSUE TITLE
企业微信推送函数有bug

### ISSUE THREAD

**Issue by qilishidai** [Wyatt1026/BilibiliDailyUp#21]
因为签到产生大量的日志进行推送，但是API只能一次性接收发1024字节。
代码虽然有判断，但是貌似没有正常执行。前1024个字节的推送可以收到，但是1024个字节后面的消息被截断遗失，企业微信无法收到。
希望大佬参考以前版本修复一下这个bug。以前版本正常的。

经过查验，可能不是utils包plus模块中的wechat_plush函数问题。可能是近期更新改动了某段代码引发的bug

**Comment by Wyatt1026** [comment]
因为我自己不用任何推送 所以无法测试  你可以断点调试看一下  是否哪里出了问题
