### ISSUE TITLE
【用户或帐号未登录或登录鉴权失败】问题

### ISSUE THREAD

**Issue by Vonalier** [Wyatt1026/BilibiliDailyUp#22]
root INFO: 50: {'errcode': 270718475, 'graphid': 33608364, 'hint': '6e5yie', 'msg': '用户或帐号未登录或登录鉴权失败', 'time': '2024-01-08 17:54:10'}

请问下这是什么原因呢？
（1）config/config.py里的COOKIE_LIST已按照规范填写了【r"DedeUserID=xxx; SESSDATA=xxx; bili_jct=xxx"】并删除了r"",中的逗号，发现提示用户或帐号未登录或登录鉴权失败
（2）设置了环境变量BILIBILI，填写【DedeUserID=xxx; SESSDATA=xxx; bili_jct=xxx】或【r"DedeUserID=xxx; SESSDATA=xxx; bili_jct=xxx"】或space.bilibili.com链接中的全部ck，也是提示用户或帐号未登录或登录鉴权失败

**Comment by Wyatt1026** [comment]
<img width="1376" alt="image" src="https://github.com/Wyatt1026/BilibiliDailyUp/assets/105420165/3bd4b5d3-c1be-4644-8c60-0a428ba5f64b">
刚刚我在本地测试了 没有问题。无法复现你的问题。
