### ISSUE TITLE
不是把cookie这样填写的吗

### ISSUE THREAD

**Issue by YcccByHe** [Wyatt1026/BilibiliDailyUp#25]
![Snipaste_2024-01-26_17-32-44](https://github.com/Wyatt1026/BilibiliDailyUp/assets/55644381/7fe07448-36b7-4c07-88a4-a460bce1d428)

**Comment by Wyatt1026** [comment]
入口函数不是给了吗。main.py. 配置文件在config.py

**Comment by Wyatt1026** [comment]
如果你只是想学习原理的话。代码已经都开源了。 对着看就好了。也没什么可以解释的

**Comment by qilishidai** [comment]
当然不是这样子填，当然如果你有能力改代码怎么填写都可以。
目前代码实现的是cookie可以填写在config.py文件里面。
另外可以配置环境变量，不过配置环境变量需要在配置文件在配置启用，然后配置环境变量BILIBILI的内容为cookie的内容。然后运行main.py
