### ISSUE TITLE
复制了正确cookie,运行报的错

### ISSUE THREAD

**Issue by WhiteCjy** [Wyatt1026/BilibiliDailyUp#4]
{
    "errorMessage": "'list'",
    "errorType": "KeyError",
    "stackTrace": [
        [
            "File \"/code/index.py\"",
            "line 16",
            "in handler",
            "bilibili.go()"
        ],
        [
            "File \"/code/bilibili.py\"",
            "line 300",
            "in go",
            "O0O000O0OO0OO00O0 .__OOO00OOOO00O0000O (O0OOOOO0O0OO0O00O )#line:426"
        ],
        [
            "File \"/code/bilibili.py\"",
            "line 200",
            "in __OOO00OOOO00O0000O",
            "OO00OO0000OOOO00O =OOOO0O0O0000OOOO0 .__O0OOO0OO00O00OO0O ()#line:317"
        ],
        [
            "File \"/code/bilibili.py\"",
            "line 89",
            "in __O0OOO0OO00O00OO0O",
            "O0O000OO0000OOOOO =OO0O00O00OOOO0O00 ['data']['list']['vlist']#line:155"
        ]
    ]
}

**Comment by ddddict** [comment]
我也是 本地能跑云函数就报这个

**Comment by Dittonal** [comment]
更新一下代码应该就好了
